name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.45.0
    with:
      install-go: true
      install-cosign: true
      install-goreleaser: true
      test-commands: make test
      report-coverage: true
      coverage-file: cover.out
